# Simple workflow for deploying static content to GitHub Pages
name: Deploy backend to Cloud Run

on:
  push:
    paths:
      - 'backend/**'
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'backend'
  cancel-in-progress: true

jobs:
  build:
    name: 'Build, Test and Deploy'
    environment: 'Google Cloud Platform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/src
    
    steps:
    - uses: 'actions/checkout@v4'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'